<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="COD-[0-9]{3}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigo_inverso"></xs:element>
                            <xs:element name="nombre"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="categoria">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Electrónica" />
                                    <xs:enumeration value="Hogar" />
                                    <xs:enumeration value="Deportes" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
            