<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Tipo simple direccion -->
  <xs:simpleType name="direccion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="norte"/>
      <xs:enumeration value="sur"/>
      <xs:enumeration value="este"/>
      <xs:enumeration value="oeste"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Elemento complejo con contenido simple y atributo metros -->
  <xs:complexType name="ubicacionCompleta">
    <xs:simpleContent>
      <xs:extension base="direccion">
        <xs:attribute name="metros" type="xs:decimal" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- Elemento raíz zonas -->
  <xs:element name="zonas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ubicacion" type="ubicacionCompleta" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
