<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <!-- Tipo base con nombre y prioridad -->
<xs:complexType name="tareaBase"> 
  <xs:sequence> 
    <xs:element name="nombre" type="xs:string"/> 
    <xs:element name="prioridad"> 
      <xs:simpleType> 
        <xs:restriction base="xs:string"> 
          <xs:enumeration value="baja"/> 
          <xs:enumeration value="media"/> 
          <xs:enumeration value="alta"/> 
        </xs:restriction> 
      </xs:simpleType> 
    </xs:element> 
  </xs:sequence> 
</xs:complexType> 

<!-- Tipo que extiende tareaBase y añade atributo completada -->
<xs:complexType name="tareaCompleta"> 
  <xs:complexContent> 
    <xs:extension base="tareaBase"> 
      <xs:attribute name="completada" type="xs:boolean" use="required"/> 
    </xs:extension> 
  </xs:complexContent> 
</xs:complexType> 

<!-- Elemento raíz lista-tareas -->
<xs:element name="lista-tareas"> 
  <xs:complexType> 
    <xs:sequence> 
      <xs:element name="tarea" type="tareaCompleta" maxOccurs="unbounded"/> 
    </xs:sequence> 
  </xs:complexType> 
</xs:element>


</xs:schema>
