<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="tipoTexto">
    <xs:restriction base="xs:string">
      <xs:minLength value="5"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoCIF">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{8}-[A-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoTel">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{9}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoArticulo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Electrónico"/>
      <xs:enumeration value="Alimentación"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoPrecio">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0.00"/>
      <xs:maxInclusive value="999.99"/>
      <xs:totalDigits value="5"/>
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>

  
  <xs:group name="datosEmpresa">
    <xs:sequence>
      <xs:element name="nombre" type="tipoTexto"/>
      <xs:element name="cif" type="tipoCIF"/>
      <xs:element name="teléfono" type="tipoTel"/>
    </xs:sequence>
  </xs:group>

  <xs:group name="datosItem">
    <xs:sequence>
      <xs:element name="descripción" type="tipoTexto"/>
      <xs:element name="cantidad" type="xs:positiveInteger"/>
      <xs:element name="oferta" minOccurs="0"/>
      <xs:element name="pvp" type="tipoPrecio"/>
    </xs:sequence>
  </xs:group>

  
  <xs:attributeGroup name="atributosPedido">
    <xs:attribute name="número" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="fecha" type="xs:date" use="required"/>
    <xs:attribute name="moneda" use="required" fixed="USD"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="atributosItem">
    <xs:attribute name="código-artículo" type="xs:string" use="required"/>
    <xs:attribute name="tipo" type="tipoArticulo" use="required"/>
  </xs:attributeGroup>

  <xs:element name="pedido">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="datos-proveedor">
          <xs:complexType>
            <xs:group ref="datosEmpresa"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="datos-cliente">
          <xs:complexType>
            <xs:group ref="datosEmpresa"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="detalle-pedido">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item">
                <xs:complexType>
                  <xs:group ref="datosItem"/>
                  <xs:attributeGroup ref="atributosItem"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="total" type="tipoPrecio" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attributeGroup ref="atributosPedido"/>
    </xs:complexType>
  </xs:element>

</xs:schema>
