<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- group por elementos -->
    <xs:group name="datosBasicosProducto">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="precio" type="xs:decimal" />
            <xs:element name="especificaciones">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="pantalla" type="xs:string"></xs:element>
                        <xs:element name="bateria" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
<!-- group por atributos -->
    <xs:attributeGroup name="identificadores">
        <xs:attribute name="id" type="xs:integer" use="required" />
        <xs:attribute name="categoria" type="xs:string" use="optional"/>
    </xs:attributeGroup>

    <xs:element name="productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="datosBasicosProducto" />
                        </xs:sequence>
                        <xs:attributeGroup ref="identificadores" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>